### ISSUE TITLE
pymod script install_all.py does not run in PyMol 2.3 

### ISSUE THREAD

**Issue by espiral17** [pymodproject/pymod#1]
I used to install the Pymod bundle installer with the  install_all.py script pretty easily. However, once I actualized PyMol to its newest version (2.3) the old, good install_all.py script does not work anymore. Many "missing parentheses" appear in the error warnings.

**Comment by mariagiuliaprado** [comment]
Hi espiral17,
Thank You for the report. This is a known issue due to the PyMod code being written in Python 2.7. Did You try to download the PyMOL 2.3 version compiled in Python 2.7? 

Anyway, we're working for porting PyMod in Python 3 and we're developing on PyMOL 2.3, so we hope to resolve this issue shortly.

While we are resolving this, the best way to use PyMod in 2.x PyMOL versions is downloading the Python2.7-compiled binary of PyMOL. You can find it here:

https://pymol.org/installers/

**Comment by paiardin** [comment]
Brava MG!

Il mar 16 apr 2019, 13:08 Maria Giulia <notifications@github.com> ha
scritto:

**Comment by giacomojanson** [comment]
A new version of PyMod (PyMod 3) has been released. It is now compatible with PyMOL 2.3 or higher. The installation process has been changed and slightly simplified (please refer to the new PyMod User's Guide).
