### ISSUE TITLE
Modeller installation problem

### ISSUE THREAD

**Issue by EunokLee** [pymodproject/pymod#7]
Hi pymod developers,

I have a problem with modeller installation. I am trying to use PyMod 3.0.2 through PyMol  2.3.3.
I am keep getting "No module named tqdm" when I am trying install modeller using the right license key.

I used command prompt on windows for pip install tqdm and the requirement already satisfied.

What am I doing wrong?

-Eunok

**Comment by paiardin** [comment]
Dear Eunok,
thank you for your question. As stated in the "requirements" section of Pymod3 homepage, "It is compatible with incentive PyMOL builds distributed by Schrodinger (required **PyMOL version >= 2.3.4**) and open source builds (required PyMOL version >= 2.3.0)."
I think therefore that the problem is due to the PyMOL version you're using (2.3.3). You could upgrade to the latest PyMOL version (2.5). 

_"I used command prompt on windows for pip install tqdm and the requirement already satisfied."_

PyMOL has its own Python interpreter. You can check by typing in the command input area of PyMOL:
`import tqdm`

to test whether the Python interpreter of PyMOL is able to find it.

All the best
PyMod team

**Comment by EunokLee** [comment]
Oops my bad - I have upgraded the PyMol and works really well. Thank you!

-Eunok
